workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.job_template: &ssh_key_configuration
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "Host *" >> ~/.ssh/config
    - echo "  StrictHostKeyChecking no" >> ~/.ssh/config
    - echo "  CheckHostIP no" >> ~/.ssh/config
    - echo "  LogLevel ERROR" >> ~/.ssh/config
    - echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config

stages:
  - mirror

mirror-code:
  <<: *ssh_key_configuration
  stage: mirror
  script: |
    git config --global user.name   gitlab-bot
    git config --global user.email "bot@example.com"

    if [[ "${CI_COMMIT_REF_NAME}" == experiment* ]]
    then
        :
    else
      git branch -f ${CI_COMMIT_REF_NAME}
      git remote set-url github "$DESTINATION_REPO"
      git push -u github "${CI_COMMIT_REF_NAME}"
    fi
