name: docs

on:
  schedule:
    - cron: 0 9 * * 1

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Make documentations
        run: |
          cd docs
          make html
