name: docs

on:
  schedule:
    - cron: 0 9 * * 1

  # Manually triggerable in github
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.7

      - name: Installation pandoc and additional libs
        run: |
          sudo apt-get install build-essential libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info

      - name: Poetry install
        run: |
          poetry run python scripts/poetry_fix.py -c
          poetry install -E all

      - name: Make documentations
        run: |
          cd docs
          poetry run make html
