name: build and publish to pypi

on:
  push:
    tags:
        - 'v*.*.*'
#   workflow_dispatch:
#     inputs:
#       tag:
#         description: 'Tag'
#         required: true
#         default: 'v0.0.0'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: JRubics/poetry-publish@v2.0
      with:
        pypi_token: ${{ secrets.LAMA_PYPI_TOKEN }}
